services:
  voice-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/voice-chat-team/voice-chat-voice-service:latest
    container_name: voice-chat-voice-service
    networks:
      - voice-chat-network
    restart: unless-stopped

networks:
  voice-chat-network:
    external: true
